"use client";

import React, { useEffect } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { SwitchStyleProvider } from "@/contexts/SwitchStyleContext";
import { DynamicThemeSwitch } from "@/components/ui/DynamicThemeSwitch";
import { NotificationProvider } from "@/components/magicui/NotificationProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 监听数据概览动画设置变化
  useEffect(() => {
    const handleStorageChange = () => {
      const isReduceMotion = localStorage.getItem('reduce-motion-enabled') === 'true';
      if (isReduceMotion) {
        document.documentElement.classList.add('reduce-motion');
      } else {
        document.documentElement.classList.remove('reduce-motion');
      }
    };

    // 初始化检查
    handleStorageChange();

    // 监听storage变化
    window.addEventListener('storage', handleStorageChange);

    // 监听自定义事件（用于同一页面内的设置变化）
    window.addEventListener('reduceMotionChanged', handleStorageChange);

    return () => {
      window.removeEventListener('storage', handleStorageChange);
      window.removeEventListener('reduceMotionChanged', handleStorageChange);
    };
  }, []);

  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <head>
        <title>行测每日记录</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SwitchStyleProvider>
            <div className="fixed top-4 right-4 z-50">
              <DynamicThemeSwitch />
            </div>
            <NotificationProvider>
              {children}
            </NotificationProvider>
          </SwitchStyleProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
