"use client";

import React, { useEffect } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { SwitchStyleProvider } from "@/contexts/SwitchStyleContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { FontProvider } from "@/contexts/FontContext";
import { BeautifulThemeSwitch } from "@/components/ui/BeautifulThemeSwitch";
import { NotificationProvider } from "@/components/magicui/NotificationProvider";
import { TooltipProvider } from "@/components/ui/tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <head>
        <title>行测每日记录</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthProvider>
            <FontProvider>
              <SwitchStyleProvider>
                <NotificationProvider>
                  <TooltipProvider>
                    <div className="fixed top-4 right-8 z-50">
                      <BeautifulThemeSwitch />
                    </div>
                    {children}
                  </TooltipProvider>
                </NotificationProvider>
              </SwitchStyleProvider>
            </FontProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
