import React, { useEffect } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { SwitchStyleProvider } from "@/contexts/SwitchStyleContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { FontProvider } from "@/contexts/FontContext";
import { NotificationProvider } from "@/components/magicui/NotificationProvider";
import { TooltipProvider } from "@/components/animate-ui/components/animate/tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <head>
        <title>行测每日记录</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@400;700&family=Noto+Sans+SC:wght@400;700&family=Source+Han+Serif+SC:wght@400;700&family=Source+Han+Sans+SC:wght@400;700&family=Inter:wght@400;500;600;700&family=Roboto:wght@400;500;700&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthProvider>
            <FontProvider>
              <SwitchStyleProvider>
                <NotificationProvider>
                  <TooltipProvider>
                    {children}
                  </TooltipProvider>
                </NotificationProvider>
              </SwitchStyleProvider>
            </FontProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}